import React, { useState } from "react";

const styles = [
  "text-red-500",
  "text-yellow-500",
  "text-green-400",
  "text-blue-500",
  "text-indigo-300",
  "text-purple-500",

  // Later will add more Tailwind CSS classes here for different styles
];

const getRandomStyle = () => {
  const randomIndex = Math.floor(Math.random() * styles.length);
  return styles[randomIndex];
};

const thoughtfulQuotes = [
  "Less is more. - Ludwig Mies van der Rohe",
  "Stay hungry, stay foolish. - Steve Jobs",
  "Live, laugh, love. - Anonymous",
  "Dream big. - Walt Disney",
  "Seize the day. - Horace",
  "Carpe diem. - Horace",
  "Be yourself. - Oscar Wilde",
  "Keep it simple. - Anonymous",
  "Think big. - Anonymous",
  "Love conquers all. - Virgil",
  "Never give up. - Winston Churchill",
  "Follow your heart. - Steve Jobs",
  "Just do it. - Nike",
  "Stay curious. - Albert Einstein",
  "Live your dream. - Les Brown",
  "Chase your passion. - Anonymous",
  "Make it happen. - Anonymous",
  "Believe in yourself. - Anonymous",
  "The power of now. - Eckhart Tolle",
  "Life is short. - Unknown",
  "Find your purpose. - Anonymous",
  "Keep moving forward. - Martin Luther King Jr.",
  "Embrace the journey. - Anonymous",
  "Stay positive. - Anonymous",
  "Learn from failure. - Anonymous",
  "Stay focused. - Anonymous",
  "Take chances. - Anonymous",
  "Live in the moment. - Anonymous",
  "Dream, believe, achieve. - Anonymous",
  "Dare to dream. - Anonymous",
  "Choose happiness. - Anonymous",
  "Stay humble. - Anonymous",
  "Find joy in life. - Anonymous",
  "Carry on. - Winston Churchill",
  "Life goes on. - Unknown",
  "Keep it real. - Anonymous",
  "Live life to the fullest. - Ernest Hemingway",
  "Create your future. - Anonymous",
  "Believe and achieve. - Napoleon Hill",
  "Think positive. - Anonymous",
  "Be the change. - Mahatma Gandhi",
  "Dream, plan, achieve. - Alfred A. Montapert",
  "Stay strong. - Anonymous",
  "Live with purpose. - Anonymous",
  "Smile, it's free therapy. - Douglas Horton",
  "Take action. - Anonymous",
  "Seize the moment. - Anonymous",
  "Love what you do. - Steve Jobs",
  "Keep calm and carry on. - Winston Churchill",
  "Stay true to yourself. - Anonymous",
  "Live with no regrets. - Anonymous",
  "Find your passion. - Anonymous",
  "Never stop learning. - Albert Einstein",
  "Live with intention. - Anonymous",
  "Stay young at heart. - Anonymous",
  "The sky's the limit. - Anonymous",
  "Think outside the box. - Anonymous",
  "Live life in color. - Anonymous",
  "Follow your bliss. - Joseph Campbell",
  "Stay weird. - Anonymous",
  "Life is beautiful. - Unknown",
  "Embrace change. - Anonymous",
  "Stay positive, work hard, make it happen. - Anonymous",
  "Be fearless. - Anonymous",
  "Live with no excuses. - Anonymous",
  "Love what you do. - Steve Jobs",
  "Keep moving forward. - Walt Disney",
  "Believe in miracles. - Anonymous",
  "Live with passion. - Tony Robbins",
  "Dare to be different. - Anonymous",
  "Keep the faith. - Anonymous",
  "Make it count. - Anonymous",
  "Stay inspired. - Anonymous",
  "Carpe diem. - Anonymous",
  "Be kind. - Anonymous",
  "Live for today. - Anonymous",
  "Be a voice, not an echo. - Albert Einstein",
  "Work hard, play hard. - Anonymous",
  "Create your own sunshine. - Anonymous",
  "Live for the moment. - Anonymous",
  "Dream big, work hard. - Anonymous",
  "Life is an adventure. - Anonymous",
  "Follow your dreams. - Anonymous",
  "Love and be loved. - Victor Hugo",
  "Believe you can. - Theodore Roosevelt",
  "Stay wild. - Anonymous",
  "Life is a gift. - Anonymous",
  "Make today amazing. - Anonymous",
  "Don't worry, be happy. - Bobby McFerrin",
  "Find your tribe. - Anonymous",
  "Do great things. - Anonymous",
  "Life is short, make it sweet. - Unknown",
  "Live a little. - Anonymous",
  "Dreams come true. - Anonymous",
  "Find joy in the journey. - Unknown",
  "Stay hungry, stay foolish. - Steve Jobs",
  "Don't look back. - Anonymous",
  "Live your life. - Anonymous",
  "Embrace the unknown. - Anonymous",
  "Carpe diem. - Anonymous",
  "Believe in miracles. - Anonymous",
  "Dream big. - Anonymous",
  "Be yourself. - Anonymous",
  "Stay curious. - Anonymous",
  "Live, laugh, love. - Anonymous",
  "Think big. - Anonymous",
  "Love conquers all. - Anonymous",
  "Seize the day. - Anonymous",
  "Keep it simple. - Anonymous",
  "Be kind. - Anonymous",
  "Make it happen. - Anonymous",
  "Believe in yourself. - Anonymous",
  "The power of now. - Anonymous",
  "Life is short. - Anonymous",
  "Find your purpose. - Anonymous",
  "Keep moving forward. - Anonymous",
  "Embrace the journey. - Anonymous",
  "Stay positive. - Anonymous",
  "Learn from failure. - Anonymous",
  "Stay focused. - Anonymous",
  "Take chances. - Anonymous",
  "Live in the moment. - Anonymous",
  "Dream, believe, achieve. - Anonymous",
  "Dare to dream. - Anonymous",
  "Choose happiness. - Anonymous",
  "Stay humble. - Anonymous",
  "Find joy in life. - Anonymous",
  "Carry on. - Anonymous",
  "Life goes on. - Anonymous",
  "Keep it real. - Anonymous",
  "Live life to the fullest. - Anonymous",
  "Create your future. - Anonymous",
  "Believe and achieve. - Anonymous",
  "Think positive. - Anonymous",
  "Be the change. - Anonymous",
  "Dream, plan, achieve. - Anonymous",
  "Stay strong. - Anonymous",
  "Live with purpose. - Anonymous",
  "Smile, it's free therapy. - Anonymous",
  "Take action. - Anonymous",
  "Seize the moment. - Anonymous",
  "Love what you do. - Anonymous",
  "Keep calm and carry on. - Anonymous",
  "Stay true to yourself. - Anonymous",
  "Live with no regrets. - Anonymous",
  "Find your passion. - Anonymous",
  "Never stop learning. - Anonymous",
  "Live with intention. - Anonymous",
  "Stay young at heart. - Anonymous",
  "The sky's the limit. - Anonymous",
  "Think outside the box. - Anonymous",
  "Live life in color. - Anonymous",
  "Follow your bliss. - Anonymous",
  "Stay weird. - Anonymous",
  "Life is beautiful. - Anonymous",
  "Embrace change. - Anonymous",
  "Stay positive, work hard, make it happen. - Anonymous",
  "Be fearless. - Anonymous",
  "Live with no excuses. - Anonymous",
  "Love what you do. - Anonymous",
  "Keep moving forward. - Anonymous",
  "Believe in miracles. - Anonymous",
  "Live with passion. - Anonymous",
  "Dare to be different. - Anonymous",
  "Keep the faith. - Anonymous",
  "Make it count. - Anonymous",
  "Stay inspired. - Anonymous",
  "Carpe diem. - Anonymous",
  "Be kind. - Anonymous",
  "Live for today. - Anonymous",
  "Be a voice, not an echo. - Anonymous",
  "Work hard, play hard. - Anonymous",
  "Create your own sunshine. - Anonymous",
  "Live for the moment. - Anonymous",
  "Dream big, work hard. - Anonymous",
  "Life is an adventure. - Anonymous",
  "Follow your dreams. - Anonymous",
  "Love and be loved. - Anonymous",
  "Believe you can. - Anonymous",
  "Stay wild. - Anonymous",
  "Life is a gift. - Anonymous",
  "Make today amazing. - Anonymous",
  "Don't worry, be happy. - Anonymous",
  "Find your tribe. - Anonymous",
  "Do great things. - Anonymous",
  "Life is short, make it sweet. - Anonymous",
  "Live a little. - Anonymous",
  "Dreams come true. - Anonymous",
  "Find joy in the journey. - Anonymous",
  "Stay hungry, stay foolish. - Steve Jobs",
  "Don't look back. - Anonymous",
  "Live your life. - Anonymous",
  "Embrace the unknown. - Anonymous",
  "Carpe diem. - Anonymous",
  "Believe in miracles. - Anonymous",
  "Dream big. - Anonymous",
  "Be yourself. - Anonymous",
  "Stay curious. - Anonymous",
  "Live, laugh, love. - Anonymous",
  "Think big. - Anonymous",
  "Love conquers all. - Anonymous",
  "Seize the day. - Anonymous",
  "Keep it simple. - Anonymous",
  "Be kind. - Anonymous",
  "Make it happen. - Anonymous",
  "Believe in yourself. - Anonymous",
  "The power of now. - Anonymous",
  "Life is short. - Anonymous",
  "Find your purpose. - Anonymous",
  "Keep moving forward. - Anonymous",
  "Embrace the journey. - Anonymous",
  "Stay positive. - Anonymous",
  "Learn from failure. - Anonymous",
  "Stay focused. - Anonymous",
  "Take chances. - Anonymous",
  "Live in the moment. - Anonymous",
  "Dream, believe, achieve. - Anonymous",
  "Dare to dream. - Anonymous",
  "Choose happiness. - Anonymous",
  "Stay humble. - Anonymous",
  "Find joy in life. - Anonymous",
  "Carry on. - Anonymous",
  "Life goes on. - Anonymous",
  "Keep it real. - Anonymous",
  "Live life to the fullest. - Anonymous",
  "Create your future. - Anonymous",
  "Believe and achieve. - Anonymous",
  "Think positive. - Anonymous",
  "Be the change. - Anonymous",
  "Dream, plan, achieve. - Anonymous",
  "Stay strong. - Anonymous",
  "Live with purpose. - Anonymous",
  "Smile, it's free therapy. - Anonymous",
  "Take action. - Anonymous",
  "Seize the moment. - Anonymous",
  "Love what you do. - Anonymous",
  "Keep calm and carry on. - Anonymous",
  "Stay true to yourself. - Anonymous",
  "Live with no regrets. - Anonymous",
  "Find your passion. - Anonymous",
  "Never stop learning. - Anonymous",
  "Live with intention. - Anonymous",
  "Stay young at heart. - Anonymous",
  "The sky's the limit. - Anonymous",
  "Think outside the box. - Anonymous",
  "Live life in color. - Anonymous",
  "Follow your bliss. - Anonymous",
  "Stay weird. - Anonymous",
  "Life is beautiful. - Anonymous",
  "Embrace change. - Anonymous",
  "Stay positive, work hard, make it happen. - Anonymous",
  "Be fearless. - Anonymous",
  "Live with no excuses. - Anonymous",
  "Love what you do. - Anonymous",
  "Keep moving forward. - Anonymous",
  "Believe in miracles. - Anonymous",
  "Live with passion. - Anonymous",
  "Dare to be different. - Anonymous",
  "Keep the faith. - Anonymous",
  "Make it count. - Anonymous",
  "Stay inspired. - Anonymous",
  "Carpe diem. - Anonymous",
  "Be kind. - Anonymous",
  "Live for today. - Anonymous",
  "Be a voice, not an echo. - Anonymous",
  "Work hard, play hard. - Anonymous",
  "Create your own sunshine. - Anonymous",
  "Live for the moment. - Anonymous",
  "Dream big, work hard. - Anonymous",
  "Life is an adventure. - Anonymous",
  "Follow your dreams. - Anonymous",
  "Love and be loved. - Anonymous",
  "Believe you can. - Anonymous",
  "Stay wild. - Anonymous",
  "Life is a gift. - Anonymous",
  "Make today amazing. - Anonymous",
  "Don't worry, be happy. - Anonymous",
  "Find your tribe. - Anonymous",
  "Do great things. - Anonymous",
  "Life is short, make it sweet. - Anonymous",
  "Live a little. - Anonymous",
  "Dreams come true. - Anonymous",
  "Find joy in the journey. - Anonymous",
  "Stay hungry, stay foolish. - Steve Jobs",
  "Don't look back. - Anonymous",
  "Live your life. - Anonymous",
  "Embrace the unknown. - Anonymous",
  "Carpe diem. - Anonymous",
  "Believe in miracles. - Anonymous",
  "Dream big. - Anonymous",
  "Be yourself. - Anonymous",
  "Stay curious. - Anonymous",
  "Live, laugh, love. - Anonymous",
  "Think big. - Anonymous",
  "Love conquers all. - Anonymous",
  "Seize the day. - Anonymous",
  "Keep it simple. - Anonymous",
  "Be kind. - Anonymous",
  "Make it happen. - Anonymous",
  "Believe in yourself. - Anonymous",
  "The power of now. - Anonymous",
  "Life is short. - Anonymous",
  "Find your purpose. - Anonymous",
  "Keep moving forward. - Anonymous",
  "Embrace the journey. - Anonymous",
  "Stay positive. - Anonymous",
  "Learn from failure. - Anonymous",
  "Stay focused. - Anonymous",
  "Take chances. - Anonymous",
  "Live in the moment. - Anonymous",
  "Dream, believe, achieve. - Anonymous",
  "Dare to dream. - Anonymous",
  "Choose happiness. - Anonymous",
  "Stay humble. - Anonymous",
  "Find joy in life. - Anonymous",
  "Carry on. - Anonymous",
  "Life goes on. - Anonymous",
  "Keep it real. - Anonymous",
  "Live life to the fullest. - Anonymous",
  "Create your future. - Anonymous",
  "Believe and achieve. - Anonymous",
  "Think positive. - Anonymous",
  "Be the change. - Anonymous",
  "Dream, plan, achieve. - Anonymous",
  "Stay strong. - Anonymous",
  "Live with purpose. - Anonymous",
  "Smile, it's free therapy. - Anonymous",
  "Take action. - Anonymous",
  "Seize the moment. - Anonymous",
  "Love what you do. - Anonymous",
  "Keep calm and carry on. - Anonymous",
  "Stay true to yourself. - Anonymous",
  "Live with no regrets. - Anonymous",
  "Find your passion. - Anonymous",
  "Never stop learning. - Anonymous",
  "Live with intention. - Anonymous",
  "Stay young at heart. - Anonymous",
  "The sky's the limit. - Anonymous",
  "Think outside the box. - Anonymous",
  "Live life in color. - Anonymous",
  "Follow your bliss. - Anonymous",
  "Stay weird. - Anonymous",
  "Life is beautiful. - Anonymous",
  "Embrace change. - Anonymous",
  "Stay positive, work hard, make it happen. - Anonymous",
  "Be fearless. - Anonymous",
  "Live with no excuses. - Anonymous",
  "Love what you do. - Anonymous",
  "Keep moving forward. - Anonymous",
  "Believe in miracles. - Anonymous",
  "Live with passion. - Anonymous",
  "Dare to be different. - Anonymous",
  "Keep the faith. - Anonymous",
  "Make it count. - Anonymous",
  "Stay inspired. - Anonymous",
  "Carpe diem. - Anonymous",
  "Be kind. - Anonymous",
  "Live for today. - Anonymous",
  "Be a voice, not an echo. - Anonymous",
  "Work hard, play hard. - Anonymous",
  "Create your own sunshine. - Anonymous",
  "Live for the moment. - Anonymous",
  "Dream big, work hard. - Anonymous",
  "Life is an adventure. - Anonymous",
  "Follow your dreams. - Anonymous",
  "Love and be loved. - Anonymous",
  "Believe you can. - Anonymous",
  "Stay wild. - Anonymous",
  "Life is a gift. - Anonymous",
  "Make today amazing. - Anonymous",
  "Don't worry, be happy. - Anonymous",
  "Find your tribe. - Anonymous",
  "Do great things. - Anonymous",
  "Life is short, make it sweet. - Anonymous",
  "Live a little. - Anonymous",
  "Dreams come true. - Anonymous",
  "Find joy in the journey. - Anonymous",
  "Stay hungry, stay foolish. - Steve Jobs",
  "Don't look back. - Anonymous",
  "Live your life. - Anonymous",
  "Embrace the unknown. - Anonymous",
  "Carpe diem. - Anonymous",
  "Believe in miracles. - Anonymous",
  "Dream big. - Anonymous",
  "Be yourself. - Anonymous",
  "Stay curious. - Anonymous",
  "Live, laugh, love. - Anonymous",
  "Think big. - Anonymous",
  "Love conquers all. - Anonymous",
  "Seize the day. - Anonymous",
  "Keep it simple. - Anonymous",
  "Be kind. - Anonymous",
  "Make it happen. - Anonymous",
  "Believe in yourself. - Anonymous",
  "The power of now. - Anonymous",
  "Life is short. - Anonymous",
  "Find your purpose. - Anonymous",
  "Keep moving forward. - Anonymous",
  "Embrace the journey. - Anonymous",
  "Stay positive. - Anonymous",
  "Learn from failure. - Anonymous",
  "Stay focused. - Anonymous",
  "Take chances. - Anonymous",
  "Live in the moment. - Anonymous",
  "Dream, believe, achieve. - Anonymous",
  "Dare to dream. - Anonymous",
  "Choose happiness. - Anonymous",
  "Stay humble. - Anonymous",
  "Find joy in life. - Anonymous",
  "Carry on. - Anonymous",
  "Life goes on. - Anonymous",
  "Keep it real. - Anonymous",
  "Live life to the fullest. - Anonymous",
  "Create your future. - Anonymous",
  "Believe and achieve. - Anonymous",
  "Think positive. - Anonymous",
  "Be the change. - Anonymous",
  "Dream, plan, achieve. - Anonymous",
  "Stay strong. - Anonymous",
  "Live with purpose. - Anonymous",
  "Smile, it's free therapy. - Anonymous",
  "Take action. - Anonymous",
  "Seize the moment. - Anonymous",
  "Love what you do. - Anonymous",
  "Keep calm and carry on. - Anonymous",
  "Stay true to yourself. - Anonymous",
  "Live with no regrets. - Anonymous",
  "Find your passion. - Anonymous",
  "Never stop learning. - Anonymous",
  "Live with intention. - Anonymous",
  "Stay young at heart. - Anonymous",
  "The sky's the limit. - Anonymous",
  "Think outside the box. - Anonymous",
  "Live life in color. - Anonymous",
  "Follow your bliss. - Anonymous",
  "Stay weird. - Anonymous",
  "Life is beautiful. - Anonymous",
  "Embrace change. - Anonymous",
  "Stay positive, work hard, make it happen. - Anonymous",
  "Be fearless. - Anonymous",
  "Live with no excuses. - Anonymous",
  "Love what you do. - Anonymous",
  "Keep moving forward. - Anonymous",
  "Believe in miracles. - Anonymous",
  "Live with passion. - Anonymous",
  "Dare to be different. - Anonymous",
  "Keep the faith. - Anonymous",
  "Make it count. - Anonymous",
  "Stay inspired. - Anonymous",
  "Carpe diem. - Anonymous",
  "Be kind. - Anonymous",
  "Live for today. - Anonymous",
  "Be a voice, not an echo. - Anonymous",
  "Work hard, play hard. - Anonymous",
  "Create your own sunshine. - Anonymous",
  "Live for the moment. - Anonymous",
  "Dream big, work hard. - Anonymous",
  "Life is an adventure. - Anonymous",
  "Follow your dreams. - Anonymous",
  "Love and be loved. - Anonymous",
  "Believe you can. - Anonymous",
  "Stay wild. - Anonymous",
  "Life is a gift. - Anonymous",
  "Make today amazing. - Anonymous",
  "Don't worry, be happy. - Anonymous",
  "Find your tribe. - Anonymous",
  "Do great things. - Anonymous",
  "Life is short, make it sweet. - Anonymous",
  "Live a little. - Anonymous",
  "Dreams come true. - Anonymous",
  "Find joy in the journey. - Anonymous",
];

const getRandomQuote = () => {
  const randomIndex = Math.floor(Math.random() * thoughtfulQuotes.length);
  return thoughtfulQuotes[randomIndex];
};

const DisplayQuotes = () => {
  const [quoteStyle] = useState(getRandomStyle());
  const [quote] = useState(getRandomQuote());

  return (
    <>
      <br />
      <div className={`text-4xl font-sans font-extrabold ${quoteStyle}`}>
        <blockquote className="flex p-4 ml-1">"{quote}"</blockquote>
      </div>
    </>
  );
};

export default DisplayQuotes;
